-- Drop old table if exists
DROP TABLE IF EXISTS users;

-- KodUser Table
CREATE TABLE IF NOT EXISTS KodUser (
  uid VARCHAR(255) PRIMARY KEY,
  username VARCHAR(255) NOT NULL UNIQUE,
  email VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  balance DECIMAL(15, 2) DEFAULT 100000.00,
  phone VARCHAR(20),
  role VARCHAR(20) DEFAULT 'Customer',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- UserToken Table
CREATE TABLE IF NOT EXISTS UserToken (
  tid SERIAL PRIMARY KEY,
  token TEXT NOT NULL,
  uid VARCHAR(255) REFERENCES KodUser(uid) ON DELETE CASCADE,
  expiry TIMESTAMP NOT NULL
);
